### PR TITLE
Add extensive error output for get_offset

### PR DESCRIPTION
**Pull request by davidanthoff**
Might help diagnose https://github.com/julia-vscode/LanguageServer.jl/issues/501.

I tried it once with a fake error, it seems to work. Not the nicest output, but hopefully we'll get what we need. Do you think this is sufficient?

### CODE REVIEW

**Comment by ZacLN** [comment]
How much overhead is there for wrapping stuff in a try block? This func gets called alot... If the overheads significant (rough guess) then can we wrap the whole function in a try block instead? (i.e. rename the existing `get_offst` -> `_get_offset` and have get_index call _get_index in a try block)

**Comment by davidanthoff** [comment]
Good point :) Here are some benchmarks:

Without try catch
```
julia> @benchmark LanguageServer.get_offset(d, 37, 8)
BenchmarkTools.Trial:
  memory estimate:  64 bytes
  allocs estimate:  1
  --------------
  minimum time:     45.501 ns (0.00% GC)
  median time:      50.960 ns (0.00% GC)
  mean time:        58.058 ns (1.94% GC)
  maximum time:     1.134 μs (93.05% GC)
  --------------
  samples:          10000
  evals/sample:     989
```
With my original implementation:
```
julia> @benchmark LanguageServer.get_offset(d, 37, 8)
BenchmarkTools.Trial:
  memory estimate:  128 bytes
  allocs estimate:  2
  --------------
  minimum time:     167.285 ns (0.00% GC)
  median time:      186.359 ns (0.00% GC)
  mean time:        201.089 ns (1.15% GC)
  maximum time:     1.669 μs (76.86% GC)
  --------------
  samples:          10000
  evals/sample:     755
```
With the new implementation that I just pushed:
```
julia> @benchmark LanguageServer.get_offset(d, 37, 8)
BenchmarkTools.Trial:
  memory estimate:  128 bytes
  allocs estimate:  2
  --------------
  minimum time:     69.928 ns (0.00% GC)
  median time:      79.609 ns (0.00% GC)
  mean time:        95.573 ns (2.44% GC)
  maximum time:     1.142 μs (87.24% GC)
  --------------
  samples:          10000
  evals/sample:     971
```
So still slower, but maybe ok? I think it would be good if we had access to the `position(io)` value, but we only get that if we start the try block after the `IOBuffer` is constructed.

**Comment by ZacLN** [comment]
That looks fine to me (I had no ballpark idea for the slow down)

**Comment by ZacLN** [comment]
Sorry, I missed the part dumping text. Can we obscure the text so that we're not getting sight of users code? Not particularly elegant or efficient but would the following work?
```julia
function obscure_text(s)
    i = 1
    io = IOBuffer()
    while i <= sizeof(s)
        di = nextind(s, i) - i
        if di == 1
            if s[i] in ('\n', '\r')
                write(io, s[i])
            else
                write(io, "a")
            end
        elseif di == 2
            write(io, "α")
        elseif di == 3
            write(io, "—")
        else
            write(io, s[i])
        end
        i += di
    end
    s1 = String(take!(io))
end
```

**Comment by davidanthoff** [comment]
Yes, that would probably work.

I think hunting that bug down will be tricky, we only had three crash reports for it from one user... So I'm not even sure we'll get more reports of this from our beta testers... Can you open a PR with this obscure stuff? I don't have much more time left today :)

**Comment by ZacLN** [comment]
Sure thing!

**Pull request merged**
