### PR TITLE
Implement semantic tokens (for highlighting)

### LINKED ISSUE #847: Support for Semantic highlight/token
If the language server implements [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) there some theming advantages to semantic tokens that users and theme-makers could use, like:

 - Function parameter names can be highlighted differently within the function body
 - It's possible to add several modificators for tokens to could be used to colorize differently for better context (example: a `const` variable can have a `const` modifier and colorized differently as a constant color of the theme)

### PR DESCRIPTION
**Pull request by FelipeLema**
Fixes #847 
pick up from #961

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation in the Julia VS Code extension docs, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG for the Julia VS Code extension, please open a PR against https://github.com/julia-vscode/julia-vscode/blob/master/CHANGELOG.md with those changes.

### CODE REVIEW

**Comment by FelipeLema** [comment]
that's weird... I thought I added the last `missing` for `TextDocumentClientCapabilities` for `semanticTokens::Union{SemanticTokensClientCapabilities,Missing}`

can we trigger CI for this again?

**Comment by PhilippPolterauer** [comment]
I would love to use this feature. Is there anyway to assist in the development?
Or maybe test it for functionality?

**Comment by FelipeLema** [comment]
the skeleton is there and it works, although it needs to be polished. Namely, the column-row indices seem to be off, but I haven't had time to pin the bug: I can see some coloring that has the row-col off, but I'm having trouble reproducing them as a minimum working example for unit tests. The bugfix should be easy, probably just a `+1` or `-1` missing somewhere... the trouble is reproducing the error.

If you've setup your IDE manually (neovim, emacs... anything but VSCode), then it should be fairly easy to point to this code and try it out:
1- clone [my repo](https://github.com/FelipeLema/LanguageServer.jl) locally
2- checkout the `semantic-tokens-847`
3- point the setup code / script to the repo you cloned

one thing that can also be worked on is adding matching cases to `semantic_token_kind()`, specially leveraging `external_env::StaticLint.ExternalEnv` for semantic context. For example, you can add the case and return an "Argument" token by copying the code for the static lint rule for "unused argument". 

I'd recommend using tests for working on `semantic_token_kind()`

**Comment by caleb-allen** [comment]
@FelipeLema was this functionality completed elsewhere?

**Comment by FelipeLema** [comment]
@caleb-allen "semantic tokens for julia language server"? not that I know of
"semantic tokens for any language"? clangd & sumneko lua

**Comment by caleb-allen** [comment]
@FelipeLema what was the reason for closing this PR?

**Comment by FelipeLema** [comment]
@caleb-allen I don't see myself finishing it in the near future. I tried squeezing some time the last few weeks, but no dice.

**Comment by caleb-allen** [comment]
@FelipeLema I'm interested in picking up where you left off, however I hit a 404 when I try to access the repo you linked above https://github.com/FelipeLema/LanguageServer.jl

Are you willing to share your latest work so that I could potentially pick it up?

**Comment by FelipeLema** [comment]
oh, I deleted that repo recently (that probably auto-closed this PR)

I've re-uploaded the `semantic-tokens-847` branch to https://codeberg.org/FelipeLema/LanguageServer.jl

**Pull request closed without merging**
