### PR TITLE
Initial InlayHint provider implementation

### PR DESCRIPTION
**Pull request by pfitzseb**
image

Todo:
- [ ] better method selection
- [x] better tooltips
- [x] take request range into account
- [x] get rid of hints in func defs
- [x] settings
  - [x] none
  - [x] all
  - [x] literals only
- [x] tests

### CODE REVIEW

**Comment by pfitzseb** [comment]
image

**Comment by fredrikekre** [comment]
> settings

Perhaps it would be useful to have `constructors` as a setting? Personally I am not sure how useful hints would be for general functions, since the argument names are like an implementation detail, but when you construct something I still think it would be useful. For example: https://github.com/julia-vscode/LanguageServer.jl/blob/5b4e8e87b5fdb8afac826f4179237bca3987a0b6/src/languageserverinstance.jl#L67-L94

**Comment by chriselrod** [comment]
I'm a fan of this feature in C++, looking forward to having it in Julia!

**Comment by ParadaCarleton** [comment]
This would be amazing to have--any more progress?

**Pull request merged**
