### PR TITLE
return DocumentSymbol instead of SymbolInformation

### PR DESCRIPTION
**Pull request by pfitzseb**
Alternative to https://github.com/julia-vscode/LanguageServer.jl/pull/881. Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/681.

Haven't tried this with a non-VSCode client yet. Would also be nice to fine tune the `detail` and `selectionRange` fields a bit. It's also a bit odd that we list function parameters here (or at least different from e.g. TS).

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation in the Julia VS Code extension docs, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG for the Julia VS Code extension, please open a PR against https://github.com/julia-vscode/julia-vscode/blob/master/CHANGELOG.md with those changes.

### CODE REVIEW

**Comment by ZacLN** [comment]
Does vscode automatically build a hierarchy if we return `DocumentSymbol`s?

**Comment by pfitzseb** [comment]
Well, this *constructs* a hierarchy, so I don't think VSCode has to do anything here.

**Comment by ZacLN** [comment]
:+1: Didn't see the push! to child part

**Review by ZacLN — APPROVED** [review]

**Comment by davidanthoff** [comment]
Can you assign to a milestone, so that I know when to merge it? :)

**Pull request merged**
