### PR TITLE
Remove file format options to avoid JuliaFormatter crash

### LINKED ISSUE #1027: formatting fails with verbose, overwrite or format_markdown in config file
Formatting a file fails if verbose, format_markdown or overwrite options are at  JuliaFormatter.toml 

```
[Error - 10:27:11 AM] Request textDocument/formatting failed.
  Message: Failed to format document: MethodError(Core.var"#Type##kw"(), ((always_use_return = true, short_to_long_function_def = false, whitespace_ops_in_indices = false, remove_extra_newlines = true, always_for_in = true, import_to_using = true, pipe_to_function_call = true, whitespace_in_kwargs = false, annotate_untyped_fields_with_any = false, conditional_to_if = true, indent_submodule = true, whitespace_typedefs = true, indent = 4, align_struct_field = true, align_assignment = true, align_conditional = true, format_docstrings = false, verbose = true, align_pair_arrow = true, format_markdown = true, margin = 94), JuliaFormatter.Options), 0xffffffffffffffff).
  Code: -32000 
```

### PR DESCRIPTION
**Pull request by dpinol**
verbose, format_markdown & overwrite options are not filtered out from JuliaFormatter.toml because they only make sense for JuliaFormat functions to format a file not for formatting a text. Passing them makes format_text crash

Fixes #1027.

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation in the Julia VS Code extension docs, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG for the Julia VS Code extension, please open a PR against https://github.com/julia-vscode/julia-vscode/blob/master/CHANGELOG.md with those changes.

### CODE REVIEW

**Comment by domluna** [comment]
this looks right to me, since the context of the formatter with vscode is on individual files.

I guess one thing to consider is if the file is .md or .jmd to allow formatting with format_markdown but that could be a separate issue since it probably requires more thought

**Comment by domluna** [comment]
the JuliaFormatter docs are outdated atm, not sure what's going on there and I keep forgetting to investigate

**Comment by dpinol** [comment]
> Alright. Docs could do with adjusting then :)
> 
> For this PR: Let's filter the allowed names by `fieldnames(JuliaFormatter.Options)`?

@pfitzseb  done (amending the previous commit)

**Review by pfitzseb — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
