### PR TITLE
Completions for unexported symbols

### PR DESCRIPTION
**Pull request by ZacLN**
@pfitzseb, as we discussed the other day - is this what you meant?

EDIT - a description
Completions are now provided for symbols that are not exported by modules in the current namespace. These are only triggered when the partial string has length > 3. Two modes are provided where:
* Completion of an unexported variable `var` from some module `m` results in the automatic inclusion of a using statement `using m: var`. This is included at the start of the current root tree and will be attached to existing `using m:...` if possible; or 
* the completion results in a qualified variable (e.g. `m.var`)

### CODE REVIEW

**Comment by pfitzseb** [comment]
Almost. What I had in mind would make this work for _all_ symbols, not only unexported ones (which may or may not be a good idea :P). Basically to counteract people using `using Foo` and then not knowing where a symbol comes from.

This feels pretty good though, so I think we could get this in as-is (although it still needs a setting in the UI, right?).

**Comment by ZacLN** [comment]
That feels a bit much for me personally but no reason to not include it as an option. Would we also want a project level action that applies that style retrospectively?

Agree on merging this as is for now

**Review by davidanthoff — CHANGES_REQUESTED** [review]
Needs a review from @pfitzseb and a merge conflict resolution.

**Review by pfitzseb — APPROVED** [review]
Alright, let's get this in!

**Review by davidanthoff — CHANGES_REQUESTED** [review]
Tests fail. Do we maybe need a tag for some dependency for this to work?

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
