### PR TITLE
Remove LS tracing

### PR DESCRIPTION
**Pull request by davidanthoff**
Replaces #266. I don't think we need this anymore, now that we have the separate trace output channel.

### CODE REVIEW

**Comment by ZacLN** [comment]
Do we know whether other editors fully support the new approach?

**Comment by davidanthoff** [comment]
No idea :) We can hold off merging this until we hear back from someone with a different editor.

**Comment by non-Jedi** [comment]
Is this removing ability to view the jsonrpc exchanged between languageserver.jl and the client? If so, as far as clients go, I can confirm that both eglot and lps-mode have the ability to view those.

**Comment by davidanthoff** [comment]
Yes, exactly, it wouldn't echo the raw JSON that is sent back and forth anymore.

So I take it that the two emacs based solutions also don't need it, I guess the other client that folks use is vim? Do we have some user who knows that and could check whether it needs it?

**Pull request closed without merging**
