### PR TITLE
Document highlight refactor

### PR DESCRIPTION
**Pull request by pfitzseb**
Factor out common code for https://github.com/julia-vscode/LanguageServer.jl/pull/908.

For every PR, please check the following:
- [ ] End-user documentation check. If this PR requires end-user documentation in the Julia VS Code extension docs, please add that at https://github.com/julia-vscode/docs.
- [ ] Changelog mention. If this PR should be mentioned in the CHANGELOG for the Julia VS Code extension, please open a PR against https://github.com/julia-vscode/julia-vscode/blob/master/CHANGELOG.md with those changes.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@pfitzseb what is the status of this? It needs a milestone and label etc.

**Comment by pfitzseb** [comment]
This is basically just a slight refactor for https://github.com/julia-vscode/LanguageServer.jl/pull/908 and should be merged at the same time as that PR.

**Review by davidanthoff — APPROVED** [review]

**Review by davidanthoff — CHANGES_REQUESTED** [review]
Needs merge conflict resolution.

**Review by davidanthoff — CHANGES_REQUESTED** [review]
At the moment tests seem to fail. Not clear to me whether that is actually related to this PR, but tests on `master` seem to pass, so my best guess is that this is somehow related to this PR?

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
