### PR TITLE
selection ranges

### LINKED ISSUE #838: Add support for SelectionRanges request
Please consider adding support for https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange.

In my experience as an IDE user/implementer, this is probably the most important feature to make writing code pleasant, as, combined with multiple cursors, it sort-of turns any editor into a structural editor.

### PR DESCRIPTION
**Pull request by ZacLN**
Fixes #838 

Not clear how to trigger these on the client side so haven't tested

### CODE REVIEW

**Comment by pfitzseb** [comment]
You can use `Shift-Alt-Right`/`Shift-Alt-Left` to expand/reduce the smart selection (which is what VSCode calls that feature). Doesn't feel too bad with this PR, imho, although there are a few cases where we iterate through too many exprs.

**Review by pfitzseb — DISMISSED** [review]

**Comment by ZacLN** [comment]
OK, let's add this as in then for the next release and then improve based on feedback (unless you have some specific ideas now)

**Comment by pfitzseb** [comment]
Initially I thought it was annoying that it takes two key strokes to get out of a string for example, but that seems to be fairly standard. So no, I don't think I have any specific ideas :)

**Comment by davidanthoff** [comment]
@ZacLN could you resolve the merge conflict?

**Review by davidanthoff — CHANGES_REQUESTED** [review]
Merge conflict needs resolution.

**Review by pfitzseb — APPROVED** [review]

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
