### PR TITLE
Improve environment handling

### PR DESCRIPTION
**Pull request by ZacLN**
https://github.com/julia-vscode/StaticLint.jl/pull/251

This is now in a state in which it's worth a discussion. 

The general idea -
* a vscode session has a 'global env', a proper env with a manifest and project file.
* Each root file (i.e. a `Document` that is not included by another one) get's assigned a subset of the packages in the global env. This assignment is done by checking which workspace folder the root doc is in. 
* A workspace folder creates a separate env if it has a project file and is part of the global env.
* 

# Example:
Global environment: `~.julia/environments/v1.7`
workspace folders `["~/.julia/dev/CSTParser", "~/.julia/dev/StaticLint"]`

I have both those projects in the global env.

* `"~/.julia/dev/CSTParser/src/CSTParser.jl"`: Gets all the dependencies specified in `"~/.julia/dev/CSTParser/Project.toml"` (they're all available from the global env). ` CSTParser` itself is not included.
* `"~/.julia/dev/CSTParser/test/runtests.jl"`: Get's the above packages but also `CSTParser` and anything included in the `extras` section of the project file.
* `"~/Documents/someotherfile.jl"`: Gets all packages from the global env (everything in the manifest, not limited to direct dependencies)

EDIT. In terms of the code - there are a lot of lines touched but most of this is just ensuring we're passing the appropriate `ExternalEnv` to various functions. Substantive changes are to `languageserverinstance.jl`, `textdocument.jl` and `staticlint.jl`

closes https://github.com/julia-vscode/julia-vscode/issues/1248

### CODE REVIEW

**Comment by pfitzseb** [comment]
We'll also need to figure out how this interacts with the env selector widget we have in VSCode, right?

**Comment by ZacLN** [comment]
Yeah, for the PR as-is the widget controls the `global env`

**Comment by pfitzseb** [comment]
Ok that's probably fine for now. I'll try to review this tonight or tomorrow.

**Comment by davidanthoff** [comment]
Would the idea be that we include this in 1.2, or for later? Should we first finish the cloud downloading stuff, and support for virtual environments? For now I'm not putting that on the list of PRs to include in 1.2, but let me know if you think otherwise.

**Pull request merged**
