### PR TITLE
update for SS changes

### PR DESCRIPTION
**Pull request by ZacLN**
https://github.com/julia-vscode/SymbolServer.jl/pull/123/

### CODE REVIEW

**Comment by davidanthoff** [comment]
StaticLint.jl v4.0.0 is also tagged, so updates to Project.toml should make this PR pass tests :)

Once this one is merged, I would release a new version to the insiders channel and unless we see regressions there for say 24 hours we release it to everyone? I think if you have some cycles right now it would be better we push this out quickly and get good feedback from the larger user base and then just fix any problems quickly. I kind of like our current rhythm of shipping new versions early and often :)

**Comment by ZacLN** [comment]
Yep that will work. This is almost certain to cause some breakages I haven't anticipated but will be able to jump on them quickly

**Comment by davidanthoff** [comment]
Hm, still some problems with tests?

**Comment by davidanthoff** [comment]
This change is not breaking, correct? So I can release a new version with a minor version bump?

**Comment by ZacLN** [comment]
yep

**Pull request merged**
