### PR TITLE
Add action for adding a docstring snippet.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Review by pfitzseb — DISMISSED** [review]
LGTM.

Do you think it'd make sense to have the action create or update the docstring (update the first line only, if necessary)?

**Comment by fredrikekre** [comment]
You mean to add the signature part if it is missing?

**Comment by pfitzseb** [comment]
That or if it's outdated.

**Comment by fredrikekre** [comment]
I made it into two different ones.

**Review by pfitzseb — APPROVED** [review]

**Pull request merged**
